version: '3.4'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: getnews
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    network_mode: host
    restart: always

  backend:
    image: backend-app
    container_name: backend
    depends_on:
      mysql:
        condition: service_healthy
    network_mode: host
    restart: always

  frontend:
    image: frontend-app
    container_name: frontend
    network_mode: host
    restart: always