version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: your_password  # Set the root password only
      MYSQL_DATABASE: getnews  # Optional: Create the 'getnews' database on startup
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

